### ISSUE TITLE
[Feature Request] Thinking about getting rid of the entering name page. 

### ISSUE THREAD

**Issue by cyfyifanchen** [rte-design/ASTRA.ai#112]
I don't think the page is meaningful.

**Comment by wangyoucao577** [comment]
What's the name page?

**Comment by cyfyifanchen** [comment]
<img width="1223" alt="image" src="https://github.com/user-attachments/assets/de3ebee0-c05d-4b8e-9b34-450105623284">

What do you think?

**Comment by wangyoucao577** [comment]
I was thought that rename `User Name` to something like `Please fill in your name`, then let the LLM/GPT model to greeting the specific name might be better.      
Many people confuses that whether they need to register account for this playground, and also can not find where to register. But what we expect is only a name to greeting.

**Comment by cyfyifanchen** [comment]
> I was thought that rename `User Name` to something like `Please fill in your name`, then let the LLM/GPT model to greeting the specific name might be better. Many people confuses that whether they need to register account for this playground, and also can not find where to register. But what we expect is only a name to greeting.

Valid point

**Comment by cyfyifanchen** [comment]
#15 Similar and relate to this issue, but different approach. Will add comments to #15.
