### ISSUE TITLE
Potentially outdated `manifest.json.elevenlabs.example`

### ISSUE THREAD

**Issue by tadaspetra** [rte-design/ASTRA.ai#149]
I couldn't get ASTRA to work using the elevenlabs example manifest.json. When I used the `manifest.json.example` and manually added replaced the `azure_tts` to the `elevenlabs_tts` it functioned properly. 

In the diff I notice two differences: 
1. It uses version `0.1.0` instead of `0.2.0`
2. Doesn't contain the `pcm_frame`.

![Screenshot 2024-08-01 at 2 11 58 PM](https://github.com/user-attachments/assets/57084a87-532d-475f-8d6b-442e8e858d55)

**Comment by cyfyifanchen** [comment]
`pcm_frame` will be removed from extension `agora_rtc` in the upcoming version, consider it fixed. :) 

BTW, nice found. @tadaspetra

**Comment by cyfyifanchen** [comment]
With the latest code, elevenlabs config is in `agents/property.json`, fill out the keys, once that's done. Swap the value in `	graphNameDefault = ""` from `config.go`, then you should be good with elevenlabs. :)
