### ISSUE TITLE
[Feature Request] When does it support visual understanding capability?

### ISSUE THREAD

**Issue by bobfu** [rte-design/ASTRA.ai#55]
I see that we have already accessed the camera capability. Will we be adding the visual understanding capability next? Currently, Gemini, GPT-4V, or 01.AI APIs all have the ability to recognize static images.

**Comment by cyfyifanchen** [comment]
Sounds like a kick-a feature, we should definitely make it in the near feature.

**Comment by cyfyifanchen** [comment]
I saw a feature video from SenseTime last week, and I think that's what you are talking about.

**Comment by plutoless** [comment]
solved in https://github.com/rte-design/ASTRA.ai/pull/137
