### ISSUE TITLE
[Doc] Tutorial for Extension and Helloworld

### ISSUE THREAD

**Issue by Lensual** [rte-design/ASTRA.ai#76]
How to develeopment an Extension.

- How to use arpm
  - What is `manifest.json` and `property.json`
  - What is the `agents` build process like
- How Extension communication. Need document for Language Interface.
- A Helloworld Extension

**Comment by cyfyifanchen** [comment]
Love the idea.

**Comment by cyfyifanchen** [comment]
We've made a tutorial showing how to connect and test using Python last week. Let's see we can arrange a section within the doc to show that to people or not.

**Comment by cyfyifanchen** [comment]
> > We've made a tutorial showing how to connect and test using Python last week. Let's see we can arrange a section within the doc to show that to people or not.
> 
> Can you send me the link to the tutorial？

We are working on polishing it up for users since we have had some updates in general from last week. I will send the link to you ASAP.

**Comment by lsm1103** [comment]
arpm是什么？怎么安装，google不到，github也搜索不到

**Comment by wangyoucao577** [comment]
It's the package manager tool for the framework. It's in build image `ghcr.io/rte-design/astra_agents_build` at the moment, will be moved out in the future.

**Comment by cyfyifanchen** [comment]
https://astra-9.gitbook.io/ten-platform/getting-started/create-a-hello-world-extension

@lsm1103 @Lensual
