### ISSUE TITLE
[Feature request] Provide a manifest.json selection option

### ISSUE THREAD

**Issue by Lensual** [rte-design/ASTRA.ai#80]
[#78 ](https://github.com/rte-design/ASTRA.ai/pull/78#issuecomment-2219554940)

1. Provide a `manifest.json` selection option
2. Online edit
3. Run as edited temporary `manifest.json` online

**Comment by cyfyifanchen** [comment]
With the latest update, `manifest.json` is no longer available. Instead tweak `./agents/property.json` and swap the values in from `graphNameDefault ` in `config.go`.

The next step is making the values as options that can be selected on the UI.
